spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authentication_service_db?createDatabaseIfNotExist=true
    username: root
    password: hung123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5       # Minimum number of idle connections in the pool
      maximum-pool-size: 20  # Maximum number of connections in the pool
      idle-timeout: 30000    # (30s) Time before an idle connection is removed
      max-lifetime: 1800000  # (30m) Maximum lifetime of a connection
      connection-timeout: 30000 # (30s) Timeout for getting a new connection
      pool-name: MyHikariPool # Custom pool name (useful for logging)

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.xml
#    enabled: true

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG